name: Ruff

on: [push]

jobs:
  ruff:
    name: Ruff lint check
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Install dependencies
        run: uv sync

      - name: Run ruff check
        run: uv run ruff check .
